import { useEffect, useRef, useState } from 'react';
import { Pressable, SafeAreaView, ScrollView, StyleSheet, Switch, Text, TextInput, View } from 'react-native';

export default function CustomerOffers({ api, authToken, onBack, onUpdated, onboarding = false }) {
  const [data,setData]=useState(null),[day,setDay]=useState(''),[month,setMonth]=useState(''),[consent,setConsent]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
  const alive=useRef(true),working=useRef(false);
  async function request(body) {
    const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),15000);
    try{const response=await fetch(api+'/customer/crm',{method:body?'PATCH':'GET',headers:{Authorization:`Bearer ${authToken}`,'Content-Type':'application/json'},cache:'no-store',signal:controller.signal,...(body?{body:JSON.stringify(body)}:{})});const result=await response.json();if(!response.ok)throw Error(result.error||'Impossible de charger tes offres.');return result;}
    finally{clearTimeout(timer);}
  }
  function apply(result){if(!alive.current)return;setData(result);setDay(result.preferences.birthday.slice(3));setMonth(result.preferences.birthday.slice(0,2));setConsent(result.preferences.personalizedOffers);onUpdated(result);}
  const load=async()=>{try{apply(await request());if(alive.current)setMessage('');}catch(error){if(alive.current)setMessage(error.name==='AbortError'?'Connexion trop lente. Réessaie.':error.message);}};
  useEffect(()=>{alive.current=true;void load();return()=>{alive.current=false;};},[authToken]);
  const save=async()=>{
    if(working.current||!data)return;
    if((day||month)&&(!/^\d{1,2}$/.test(day)||!/^\d{1,2}$/.test(month)))return setMessage('Renseigne le jour et le mois, ou laisse les deux vides.');
    working.current=true;setBusy(true);setMessage('');
    try{apply(await request({birthday:day&&month?`${month.padStart(2,'0')}-${day.padStart(2,'0')}`:'',personalizedOffers:consent}));if(alive.current){if(onboarding)onBack();else setMessage('Tes choix sont enregistrés.');}}
    catch(error){if(alive.current)setMessage(error.name==='AbortError'?'Réponse trop lente. Réessaie pour confirmer l’enregistrement.':error.message);}
    finally{working.current=false;if(alive.current)setBusy(false);}
  };
  return <SafeAreaView style={s.page}><ScrollView contentContainerStyle={s.content} keyboardShouldPersistTaps="handled">
    <Pressable accessibilityRole="button" disabled={busy} onPress={onBack} style={s.back}><Text style={s.backText}>{onboarding?'Passer cette étape ›':'‹ Mon compte'}</Text></Pressable>
    <Text style={s.title}>{onboarding?'Un petit plus pour toi ?':'Mes offres'}</Text><Text style={s.intro}>Ton anniversaire et tes envies, seulement si tu le souhaites.</Text>
    <View style={s.card}><Text style={s.heading}>Ton anniversaire · facultatif</Text><Text style={s.copy}>Indique le jour et le mois pour qu’une offre puisse être préparée la veille, si le restaurant active ce programme. Pas besoin de ton année de naissance.</Text><View style={s.row}><View style={s.half}><Text style={s.label}>Jour</Text><TextInput accessibilityLabel="Jour de naissance" value={day} onChangeText={setDay} keyboardType="number-pad" maxLength={2} placeholder="JJ" style={s.input} editable={!!data&&!busy} /></View><View style={s.half}><Text style={s.label}>Mois</Text><TextInput accessibilityLabel="Mois de naissance" value={month} onChangeText={setMonth} keyboardType="number-pad" maxLength={2} placeholder="MM" style={s.input} editable={!!data&&!busy} /></View></View><Text style={s.note}>Pour effacer cette information, vide les deux champs puis enregistre.</Text></View>
    <View style={s.card}><View style={s.row}><Text style={[s.heading,{flex:1}]}>Offres personnalisées</Text><Switch accessibilityLabel="Accepter les offres personnalisées" value={consent} onValueChange={setConsent} disabled={!data||busy} trackColor={{false:'#cbb8ae',true:'#397353'}} /></View><Text style={s.copy}>J’accepte que Bibou utilise mon historique de commandes (fréquence et montants) et mon anniversaire si renseigné, pour me proposer des bons adaptés dans mon compte. Facultatif et désactivable ici à tout moment.</Text><Text style={s.note}>Aucun SMS ni e-mail publicitaire. Pour recevoir aussi un push, active séparément les promotions dans Mes notifications. Tes points habituels restent disponibles sans ces offres.</Text></View>
    <Pressable accessibilityRole="button" style={[s.button,(!data||busy)&&s.dim]} disabled={!data||busy} onPress={save}><Text style={s.buttonText}>{busy?'Enregistrement…':onboarding?'Enregistrer et continuer':'Enregistrer mes choix'}</Text></Pressable>
    {!!message&&<Text accessibilityLiveRegion="polite" style={s.feedback}>{message}</Text>}{!data&&<Pressable accessibilityRole="button" onPress={load} style={s.back}><Text style={s.backText}>Réessayer le chargement</Text></Pressable>}
    {!onboarding&&<><Text style={s.section}>Tes bons personnels</Text>{data?.offers.length?data.offers.map(o=><View key={o.id} style={s.card}><Text style={s.badge}>−{o.discountPercent} %</Text><Text style={s.heading}>{o.title}</Text><Text style={s.copy}>Sur les produits{ o.minSubtotal>0?` dès ${o.minSubtotal.toFixed(2).replace('.',',')} € de produits`:''}, hors livraison. Jusqu’au {new Date(o.expiresAt).toLocaleString('fr-FR',{timeZone:'Europe/Paris'})} (heure de Paris).</Text><Text style={s.note}>{o.status==='available'?'La meilleure remise s’appliquera automatiquement au paiement, sans cumul avec la bienvenue ou les 5 % Bibou +.':o.status==='reserved'?'Ce bon est réservé pendant ton paiement en cours.':'Bon déjà utilisé.'}</Text></View>):<View style={s.card}><Text style={s.copy}>{data?'Aucun bon disponible pour le moment.':'Chargement des bons…'}</Text></View>}<Text style={s.footer}>Bon personnel à usage unique après paiement, y compris si la commande est annulée ensuite. La livraison offerte Bibou + reste compatible. Désactiver les offres bloque les nouvelles attributions, sans retirer les bons déjà accordés.</Text></>}
  </ScrollView></SafeAreaView>;
}
const s=StyleSheet.create({page:{flex:1,backgroundColor:'#E95122'},content:{padding:22,maxWidth:680,width:'100%',alignSelf:'center',paddingBottom:50},back:{paddingVertical:15},backText:{fontWeight:'800',color:'#231711'},title:{fontSize:32,fontWeight:'900',color:'white',marginTop:10},intro:{color:'white',fontSize:16,lineHeight:24,marginVertical:18},card:{backgroundColor:'#FFFBF6',padding:20,borderRadius:20,marginBottom:16},heading:{fontSize:18,fontWeight:'800',color:'#29201d',marginBottom:10},copy:{fontSize:14,lineHeight:22,color:'#4e3b30'},note:{fontSize:12,lineHeight:20,color:'#66554b',marginTop:12},row:{flexDirection:'row',gap:15,alignItems:'center'},half:{flex:1},label:{fontSize:13,fontWeight:'800',marginTop:15,marginBottom:6},input:{borderWidth:1,borderColor:'#bfac9d',borderRadius:10,padding:14,fontSize:16,color:'#29201d'},button:{backgroundColor:'#241a16',padding:18,borderRadius:15},buttonText:{color:'white',fontWeight:'800',textAlign:'center'},dim:{opacity:.5},feedback:{backgroundColor:'#fff0dd',padding:15,borderRadius:12,marginTop:15,lineHeight:22},section:{fontWeight:'900',color:'white',fontSize:23,marginTop:30,marginBottom:15},badge:{fontWeight:'900',color:'#9c341b',fontSize:28,marginBottom:10},footer:{lineHeight:21,fontSize:12,color:'#331c12'}});
