import React, { useState } from 'react';
import { View, Text, Pressable, StyleSheet } from 'react-native';
const money = n => Number(n).toFixed(2).replace('.', ',') + ' €';
function Basket({ title, basket }) {
  return <View style={s.basket}><Text style={s.bold}>{title}</Text>{basket.items.map((item,i)=><View key={i} style={s.line}><Text>{item.quantity} × {item.name} · {money(item.quantity*item.price)}</Text>{item.options?.length>0 && <Text style={s.small}>{item.options.map(o=>o.label).join(' · ')}</Text>}</View>)}<Text>Articles : {money(basket.subtotal)} · Réduction : {money(basket.discount || 0)}</Text><Text>Livraison : {money(basket.deliveryFee || 0)}</Text><Text style={s.bold}>Total : {money(basket.total)}</Text></View>;
}
export default function OrderAmendments({ orders, onDecide, busy }) {
  const [refusing, setRefusing] = useState(null);
  return <>{orders.filter(o=>o.amendment).map(order=>{
    const a=order.amendment, pending=order.status==='awaiting_customer' && a.status==='pending';
    const expired=Date.parse(a.expiresAt)<=Date.now();
    const key=order.apiId+':'+a.revision;
    return <View key={key} style={s.card} accessibilityLiveRegion="polite"><Text style={s.title}>{order.id} · {pending ? 'Ton accord est nécessaire' : order.status==='cancelled' ? 'Commande annulée' : a.status==='accepted' ? 'Nouveau panier validé' : 'Commande annulée'}</Text><Text>{a.proposal.reason}</Text>{pending && <><Text style={s.notice}>Le restaurant a proposé de modifier ta commande. Vérifie les articles et les options avant de répondre.</Text><Text>Réponse avant {new Date(a.expiresAt).toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'})}. Sans réponse à temps, la commande sera annulée.</Text><Basket title="Panier initial" basket={a.original}/><Basket title="Panier proposé" basket={a.proposal}/><Text style={s.bold}>{a.proposal.refundAmount>0 ? `${money(a.proposal.refundAmount)} à rembourser par le restaurant dans SumUp si tu acceptes. Le remboursement n’est pas automatique.` : 'Le montant payé ne change pas. Aucun nouveau paiement.'}</Text>{expired ? <Text>Le délai est écoulé. Actualise le suivi pour voir l’annulation.</Text> : <><Pressable accessibilityRole="button" disabled={busy} style={[s.accept,busy&&s.disabled]} onPress={()=>onDecide(order,'accept')}><Text style={s.white}>{busy?'Enregistrement…':'Accepter le nouveau panier'}</Text></Pressable>{refusing===key ? <View><Text>Refuser annule toute la commande. Le restaurant devra rembourser le montant payé.</Text><Pressable accessibilityRole="button" disabled={busy} style={s.refuse} onPress={()=>onDecide(order,'refuse')}><Text>Confirmer le refus et l’annulation</Text></Pressable><Pressable accessibilityRole="button" onPress={()=>setRefusing(null)}><Text>Revenir à la proposition</Text></Pressable></View> : <Pressable accessibilityRole="button" disabled={busy} style={s.refuse} onPress={()=>setRefusing(key)}><Text>Refuser et annuler la commande</Text></Pressable>}</>}</>}{!pending && a.status==='accepted' && <Basket title="Panier accepté" basket={a.proposal}/>}<Text>Montant payé : {money(order.paidTotal ?? a.original.total)}</Text>{order.refund && <Text style={s.notice}>{order.refund.status==='due' ? `Remboursement de ${money(order.refund.amount)} à effectuer par le restaurant. Contacte-le si nécessaire.` : `Le restaurant a déclaré avoir effectué le remboursement de ${money(order.refund.amount)}. Le délai de réception dépend de ta banque.`}</Text>}</View>;
  })}</>;
}
const s=StyleSheet.create({card:{backgroundColor:'#FFF3D9',borderRadius:16,padding:18,marginBottom:18,gap:12},title:{fontSize:20,fontWeight:'700',color:'#34291D'},bold:{fontWeight:'700',color:'#34291D'},basket:{backgroundColor:'#fff',padding:14,borderRadius:10,gap:8},line:{gap:4,marginVertical:4},small:{fontSize:13,color:'#5E564B'},notice:{lineHeight:22,color:'#6C431B'},accept:{padding:16,backgroundColor:'#397353',borderRadius:10,alignItems:'center'},white:{color:'#fff',fontWeight:'700'},refuse:{padding:14,borderWidth:1,borderColor:'#9B3E28',borderRadius:10,alignItems:'center'},disabled:{opacity:.5}});
