const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),os=require('node:os'),path=require('node:path');
const {spawn}=require('node:child_process'),{once}=require('node:events');
const {createCustomerSession}=require('./customer-session');
const {immediateService}=require('./kiosk-immediate');
test('immediate kiosk service is device-only, has no reservation or customer-selected time',()=>{
  const input={method:'pickup',kioskService:{mode:'here'}};
  const result=immediateService(input,true,new Date('2026-10-10T19:17:00Z'));
  assert.deepEqual(result,{serviceDate:'2026-10-10',slot:'21:17',kioskImmediate:true,kioskDiningMode:'here',dineIn:true});
  assert.throws(()=>immediateService(input,false),/Accès borne/);
  for(const patch of [{slot:'19:00'},{serviceDate:'2026-10-11'},{tableReservation:{}},{method:'delivery'},{kioskService:{mode:'here',delay:5}},{kioskService:{mode:'bad'}}]) assert.throws(()=>immediateService({...input,...patch},true),/invalide/);
  assert.equal(immediateService({method:'pickup'},false),null);
});
test('guest kiosk HTTP: no phone, no slot, safe card preparation, cash staff collection, session isolation', {timeout:30000},async t=>{
  const dir=await fs.mkdtemp(path.join(os.tmpdir(),'bibou-immediate-http-')),file=path.join(dir,'data.json');
  const customer={id:'fictional-registered-owner',name:'Camille Test',firstName:'Camille',lastName:'Test',phone:'+33600000000',points:0};
  await fs.writeFile(file,JSON.stringify({customers:[customer],orders:[],nextOrderNumber:1}));
  const secret='fictional-immediate-device-secret-at-least-32-characters',signing='fictional-immediate-signing';
  const child=spawn(process.execPath,[path.join(__dirname,'server.js')],{cwd:dir,env:{PATH:process.env.PATH,NODE_ENV:'test',PORT:'0',DATA_FILE_PATH:file,SESSION_SECRET:signing,KIOSK_PAIRING_ENABLED:'true',KIOSK_TERMINAL_ENABLED:'true',KIOSK_TERMINAL_DEVICE_SECRET:secret,RESTAURANT_DASHBOARD_PASSWORD:'fictional-password',SUMUP_API_KEY:'fictional-unused-no-charge',SUMUP_MERCHANT_CODE:'FAKE_MERCHANT',SUMUP_KIOSK_AFFILIATE_KEY:'sup_afk_fictional'},stdio:['ignore','pipe','pipe']});
  t.after(async()=>{child.kill();if(child.exitCode===null)await once(child,'exit');await fs.rm(dir,{recursive:true,force:true});});
  const base=await new Promise((resolve,reject)=>{let out='',err='';child.stderr.on('data',x=>err+=x);child.stdout.on('data',x=>{out+=x;const m=out.match(/http:\/\/localhost:(\d+)/);if(m)resolve(`http://127.0.0.1:${m[1]}/api`);});child.once('exit',()=>reject(Error(err)));child.once('error',reject);});
  const call=async(route,body,auth='',device=secret,method=body?'POST':'GET')=>{const r=await fetch(base+route,{method,headers:{'Content-Type':'application/json',...(auth?{Authorization:`Bearer ${auth}`}:{}) ,...(device?{'x-bibou-kiosk-token':device}:{})},...(body?{body:JSON.stringify(body)}:{})});return{status:r.status,data:await r.json()};};
  assert.equal((await call('/kiosk/guest',{},'','')).status,403);
  assert.equal((await call('/kiosk/guest',{phone:'0600000000'})).status,400);
  const login=await call('/kiosk/guest',{});assert.equal(login.status,201,JSON.stringify(login));
  const guest=login.data.customer,token=login.data.token;
  assert.ok(guest.isKioskGuest);assert.equal(guest.phone,'');assert.ok(token);
  const input={customerId:guest.id,method:'pickup',paymentMethod:'card',requestId:'fictional-immediate-card-0001',kioskService:{mode:'here'},items:[{productId:'classique',quantity:1,price:0.01,selections:[{groupId:'protein',id:'vegetarian'},{groupId:'salad',id:'sans-crudites'},{groupId:'sauces',id:'bleu'}]}]};
  assert.equal((await call('/orders',input,token,'')).status,401);
  assert.equal((await call('/orders',{...input,customerId:customer.id},token)).status,401);
  assert.equal((await call('/orders',{...input,slot:'19:40'},token)).status,400);
  assert.equal((await call('/orders',{...input,kioskService:undefined},token)).status,400);
  const created=await Promise.all([call('/orders',input,token),call('/orders',input,token)]);
  assert.deepEqual(created.map(r=>r.status).sort(),[200,201],JSON.stringify(created));
  const order=created[0].data.order;
  assert.equal(order.kioskImmediate,true);assert.equal(order.kioskGuest,true);assert.equal(order.dineIn,true);assert.equal(order.kioskDiningMode,'here');assert.equal(order.slotDurationMinutes,0);
  assert.ok(order.total>0.01);assert.notEqual(order.payment?.status,'PAID');
  assert.match(order.items[0].options.find(x=>x.groupId==='protein').label,/sans viande, bacon ni lard/);
  assert.equal((await call('/orders',{...input,kioskService:{mode:'take'}},token)).status,409);
  const prepared=await call('/kiosk/terminal/prepare',{orderId:order.id},token);assert.equal(prepared.status,200,JSON.stringify(prepared));assert.equal(prepared.data.payment.canLaunch,true);
  const again=await call('/kiosk/terminal/prepare',{orderId:order.id},token);assert.equal(again.data.payment.canLaunch,false);
  const secondGuest=await call('/kiosk/guest',{}),secondToken=secondGuest.data.token;
  assert.notEqual(secondGuest.data.customer.id,guest.id);
  assert.equal((await call('/kiosk/terminal/prepare',{orderId:order.id},secondToken)).status,401);
  assert.equal((await call('/customer/wheel',null,token)).status,403);
  assert.equal((await call('/customer/wheel/spin',{},token)).status,403);
  const cash=await call('/orders',{...input,paymentMethod:'cash',requestId:'fictional-immediate-cash-0002',kioskService:{mode:'take'}},token);assert.equal(cash.status,201,JSON.stringify(cash));
  assert.equal(cash.data.order.payment.status,'CASH_DUE');assert.equal(cash.data.order.dineIn,false);
  assert.equal((await call('/kiosk/terminal/prepare',{orderId:cash.data.order.id},token)).status,409);
  const staff=(await call('/dashboard/auth/login',{password:'fictional-password'})).data.token;
  const collect=()=>call(`/dashboard/orders/${cash.data.order.id}/cash`,{action:'confirm',amount:cash.data.order.total},staff);
  const paid=await collect();assert.equal(paid.status,200,JSON.stringify(paid));assert.equal(paid.data.order.payment.status,'PAID');assert.equal(paid.data.order.status,'confirmed');
  assert.equal((await collect()).status,200);
  const persisted=JSON.parse(await fs.readFile(file,'utf8'));assert.equal(persisted.customers.length,1);assert.equal(persisted.customers[0].points,0);assert.equal(persisted.orders.length,2);
  const registeredToken=createCustomerSession(customer.id,signing);
  const registered={...input,customerId:customer.id,requestId:'fictional-immediate-registered-0003'};
  assert.equal((await call('/orders',registered,registeredToken,'')).status,403);
  const registeredResult=await call('/orders',registered,registeredToken);assert.equal(registeredResult.status,201,JSON.stringify(registeredResult));assert.equal(registeredResult.data.order.kioskGuest,false);
  assert.equal((await call('/orders',{...registered,kioskService:undefined,requestId:'fictional-normal-no-time-0004'},registeredToken,'')).status,400);
  assert.equal((await call('/kiosk-pairing/end',{},token)).status,200);
  assert.equal((await call('/orders',{...input,requestId:'fictional-ended-guest-0005'},token)).status,401);
});
