const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),os=require('node:os'),path=require('node:path');
const {spawn}=require('node:child_process'),{once}=require('node:events');
const {createCustomerSession}=require('./customer-session'),{parisDateKey}=require('./availability');
test('cash HTTP: device, owner, immutable method, duplicate prevention, staff collection and revenue', {timeout:30000},async t=>{
  const dir=await fs.mkdtemp(path.join(os.tmpdir(),'bibou-cash-http-')),file=path.join(dir,'data.json');
  const customer={id:'fictional-cash-owner',name:'Camille Test',firstName:'Camille',lastName:'Test',phone:'+33600000000',points:0};
  await fs.writeFile(file,JSON.stringify({customers:[customer],orders:[],nextOrderNumber:1}));
  const secret='fictional-cash-device-secret-at-least-32-characters',signing='fictional-signing';
  const child=spawn(process.execPath,[path.join(__dirname,'server.js')],{cwd:dir,env:{PATH:process.env.PATH,NODE_ENV:'test',PORT:'0',DATA_FILE_PATH:file,SESSION_SECRET:signing,KIOSK_TERMINAL_ENABLED:'true',KIOSK_TERMINAL_DEVICE_SECRET:secret,RESTAURANT_DASHBOARD_PASSWORD:'fictional-password'},stdio:['ignore','pipe','pipe']});
  t.after(async()=>{child.kill();if(child.exitCode===null)await once(child,'exit');await fs.rm(dir,{recursive:true,force:true});});
  const base=await new Promise((resolve,reject)=>{let out='',err='';child.stderr.on('data',x=>err+=x);child.stdout.on('data',x=>{out+=x;const m=out.match(/http:\/\/localhost:(\d+)/);if(m)resolve(`http://127.0.0.1:${m[1]}/api`);});child.once('exit',()=>reject(Error(err)));child.once('error',reject);});
  const token=createCustomerSession(customer.id,signing),other=createCustomerSession('other-person',signing);
  const call=async(route,body,auth=token,device=secret,method=body?'POST':'GET')=>{const r=await fetch(base+route,{method,headers:{'Content-Type':'application/json',Authorization:`Bearer ${auth}`,...(device?{'x-bibou-kiosk-token':device}:{})},...(body?{body:JSON.stringify(body)}:{})});return{status:r.status,data:await r.json()};};
  const tomorrow=new Date(Date.now()+86400000);
  const input={customerId:customer.id,method:'pickup',paymentMethod:'cash',requestId:'fictional-cash-attempt-0001',serviceDate:parisDateKey(tomorrow),slot:'19:40',slotGrid:20,items:[{productId:'classique',quantity:1,price:0.01,selections:[{groupId:'protein',id:'viande'},{groupId:'salad',id:'roquette'},{groupId:'sauces',id:'mayo'}]}]};
  assert.equal((await call('/orders',input,token,'')).status,403);
  assert.equal((await call('/orders',input,other)).status,401);
  assert.equal((await call('/orders',{...input,method:'delivery'})).status,403);
  const created=await Promise.all([call('/orders',input),call('/orders',input)]);
  assert.deepEqual(created.map(r=>r.status).sort(),[200,201],JSON.stringify(created));
  const order=created[0].data.order;assert.equal(order.payment.status,'CASH_DUE');assert.ok(order.total>0.01);
  assert.equal((await call('/orders',{...input,paymentMethod:'card'})).status,409);
  assert.equal((await call('/kiosk/terminal/prepare',{orderId:order.id})).status,409);
  assert.equal((await call('/payments/sumup-checkout',{orderId:order.id})).status,409);
  assert.equal((await call(`/dashboard/orders/${order.id}/cash`,{action:'confirm',amount:order.total})).status,401);
  const login=await call('/dashboard/auth/login',{password:'fictional-password'},'');const staff=login.data.token;
  const before=await call('/dashboard/orders',null,staff);assert.equal(before.data.orders.length,1);assert.equal(before.data.revenue.today,0);
  assert.equal((await call(`/dashboard/orders/${order.id}`,{status:'accepted'},staff,secret,'PATCH')).status,409);
  assert.equal((await call(`/dashboard/orders/${order.id}/cash`,{action:'confirm',amount:0.01},staff)).status,409);
  const collect=()=>call(`/dashboard/orders/${order.id}/cash`,{action:'confirm',amount:order.total},staff);
  const paid=await collect();assert.equal(paid.status,200,JSON.stringify(paid));assert.equal(paid.data.order.payment.status,'PAID');assert.equal(paid.data.order.status,'confirmed');
  const points=(JSON.parse(await fs.readFile(file,'utf8'))).customers[0].points;assert.ok(points>0);
  assert.equal((await collect()).status,200);assert.equal((JSON.parse(await fs.readFile(file,'utf8'))).customers[0].points,points);
  const cashTwo=await call('/orders',{...input,requestId:'fictional-cash-attempt-0002'});assert.equal(cashTwo.status,201);
  const cancel=await call(`/dashboard/orders/${cashTwo.data.order.id}/cash`,{action:'cancel'},staff);assert.equal(cancel.data.order.status,'cancelled');
  assert.equal((await call(`/dashboard/orders/${cashTwo.data.order.id}/cash`,{action:'confirm',amount:cashTwo.data.order.total},staff)).status,409);
  assert.equal((JSON.parse(await fs.readFile(file,'utf8'))).orders.length,2);
});
