const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { createKioskConnectionStore, kioskRequestAllowed, kioskCustomerView, orderInKioskSession, SESSION_MS } = require('./kiosk-connections');
const { parseKioskQr, kioskPhoneUrl, kioskPairingFromLocation } = require('../kiosk-qr-client');
test('persistent QR approval issues only a temporary device-bound session and revokes it', t => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'bibou-connection-unit-'));
  t.after(() => fs.rmSync(dir, { recursive: true, force: true }));
  const file = path.join(dir, 'connections.json'), device = 'fictional-device-with-more-than-32-chars';
  let time = Date.now(); const options = { secret: 'fictional-signing-key', now: () => time };
  const first = createKioskConnectionStore(file, options), pairing = first.create('Borne fictive');
  const proof = parseKioskQr(pairing.qr);
  assert.equal(first.poll(pairing.session, pairing.readerSecret, device).status, 'pending');
  const restarted = createKioskConnectionStore(file, options);
  restarted.approve(proof, 'fictional-customer');
  assert.throws(() => restarted.poll(pairing.session, proof.code, device));
  const connected = restarted.poll(pairing.session, pairing.readerSecret, device);
  assert.equal(connected.session.customerId, 'fictional-customer');
  assert.equal(connected.session.expiresAt, time + SESSION_MS);
  assert.equal(first.read(connected.token, 'other-fictional-device-with-32-chars'), null);
  assert.ok(first.read(connected.token, device));
  assert.throws(() => first.poll(pairing.session, pairing.readerSecret, device));
  assert.equal(fs.readFileSync(file, 'utf8').includes(connected.token), false);
  assert.equal(fs.readFileSync(file, 'utf8').includes(pairing.readerSecret), false);
  first.revoke(connected.token, device);
  assert.equal(restarted.read(connected.token, device), null);
  const next = first.create('Borne fictive'); first.approve(parseKioskQr(next.qr), 'fictional-customer');
  const issued = first.poll(next.session, next.readerSecret, device); time += SESSION_MS;
  assert.equal(first.read(issued.token, device), null);
});
test('only the same device and account can recover the locally journalled pending order', t => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'bibou-recover-unit-'));
  t.after(() => fs.rmSync(dir, { recursive: true, force: true }));
  const store = createKioskConnectionStore(path.join(dir, 'connections.json'), { secret: 'fake' }), device = 'fictional-terminal-device-secret-long';
  const first = store.create('Borne fictive'); store.approve(parseKioskQr(first.qr), 'fictional');
  const result = store.poll(first.session, first.readerSecret, device), session = result.session;
  const order = { id: 'pending-fake', customerId: 'fictional', kioskDeviceDigest: session.deviceDigest, kioskSessionId: 'previous-session' };
  assert.equal(orderInKioskSession(order, session), false);
  assert.equal(store.recoverOrder(result.token, device, { ...order, customerId: 'someone-else' }), false);
  assert.equal(store.recoverOrder(result.token, device, { ...order, kioskDeviceDigest: 'wrong' }), false);
  assert.ok(store.recoverOrder(result.token, device, order));
  assert.equal(orderInKioskSession(order, store.read(result.token, device)), true);
  assert.equal(orderInKioskSession({ id: 'other-old-order' }, store.read(result.token, device)), false);
});
test('scoped session cannot alter an account, consent, subscription or access restaurant routes', () => {
  for (const [method, route] of [['DELETE', '/api/customer/account'], ['PATCH', '/api/customers/fake'], ['PATCH', '/api/customer/push'], ['POST', '/api/bibou-plus/checkout'], ['POST', '/api/kiosk-pairing/approve'], ['GET', '/api/dashboard/customers'], ['POST', '/api/payments/sumup-checkout']]) assert.equal(kioskRequestAllowed(method, route), false);
  assert.ok(kioskRequestAllowed('GET', '/api/auth/me'));
  assert.ok(kioskRequestAllowed('POST', '/api/kiosk/terminal/verify'));
  const visible = kioskCustomerView({ id: 'fake', firstName: 'Camille', points: 12, bibouPlusExpiresAt: 'future', address: 'private', email: 'private', sponsorCode: 'private', welcomeReward: { status: 'used', usedOrderId: 'private-old-order' } });
  assert.equal(visible.address, undefined); assert.equal(visible.email, undefined); assert.equal(visible.welcomeReward.usedOrderId, undefined); assert.equal(visible.points, 12); assert.equal(visible.bibouPlusExpiresAt, 'future');
});
test('phone camera QR uses only the official HTTPS link and keeps the proof out of HTTP query strings', () => {
  const qr = `bibousburgers://borne/connexion?session=${'a'.repeat(32)}&code=${'b'.repeat(43)}`;
  const url = kioskPhoneUrl(qr);
  assert.equal(new URL(url).search, '');
  assert.deepEqual(parseKioskQr(url), parseKioskQr(qr));
  assert.deepEqual(kioskPairingFromLocation(url), parseKioskQr(qr));
  assert.equal(kioskPairingFromLocation(url.replace('onrender.com', 'example.com')), null);
  for (const invalid of [url + '&token=secret', url.replace('/borne/connexion', '/other'), url.replace('https:', 'http:'), url.replace('#', '?'), url.replace('onrender.com', 'onrender.com.evil.invalid')]) assert.throws(() => parseKioskQr(invalid));
});
