const test = require('node:test'), assert = require('node:assert/strict'), fs = require('node:fs/promises'), os = require('node:os'), path = require('node:path'), crypto = require('node:crypto');
const { spawn } = require('node:child_process'), { once } = require('node:events');
const { createCustomerSession } = require('./customer-session'), sms = require('./marketing-sms');
test('API SMS : lecture sans migration, accord explicite, authentification, STOP et envoi inactif', { timeout: 20000 }, async t => {
  const dir = await fs.mkdtemp(path.join(os.tmpdir(), 'bibou-marketing-sms-test-')), file = path.join(dir, 'data.json'), secret = 'sms-http-secret-only-'.repeat(3);
  const original = JSON.stringify({ customers: [{ id: 'c1', name: 'Fictif', phone: '+33600000001', crmPreferences: { personalizedOffers: true } }, { id: 'c2', name: 'Autre fictif', phone: '+33600000002' }], orders: [] });
  await fs.writeFile(file, original);
  const child = spawn(process.execPath, [path.join(__dirname, 'server.js')], { cwd: dir, env: { PATH: process.env.PATH, NODE_ENV: 'test', PORT: '0', DATA_FILE_PATH: file, SESSION_SECRET: secret, RESTAURANT_DASHBOARD_PASSWORD: 'sms-only-fake', SMS_MARKETING_FROM: 'BibouBurger', SMS_MARKETING_PUBLIC_ORIGIN: 'https://fake.example' }, stdio: ['ignore', 'pipe', 'pipe'] });
  t.after(async () => { child.kill(); if (child.exitCode === null) await once(child, 'exit'); await fs.rm(dir, { recursive: true, force: true }); });
  const base = await new Promise((resolve, reject) => { child.stdout.on('data', v => { const m = String(v).match(/http:\/\/localhost:\d+/); if (m) resolve(m[0]); }); child.on('error', reject); child.on('exit', code => reject(Error('server ' + code))); });
  const req = (route, auth = '', method = 'GET', input) => fetch(base + route, { method, headers: { Authorization: 'Bearer ' + auth, 'Content-Type': 'application/json' }, ...(input ? { body: JSON.stringify(input) } : {}) });
  const c1 = createCustomerSession('c1', secret), c2 = createCustomerSession('c2', secret);
  const admin = (await (await req('/api/dashboard/auth/login', '', 'POST', { password: 'sms-only-fake' })).json()).token;
  assert.equal((await req('/api/customer/marketing-sms')).status, 401);
  assert.equal((await req('/api/customer/marketing-sms', admin)).status, 401);
  assert.equal((await req('/api/dashboard/marketing-sms', c1)).status, 401);
  const initial = await req('/api/dashboard/marketing-sms', admin); assert.equal(initial.headers.get('cache-control'), 'no-store'); assert.equal((await initial.json()).optedInCustomers, 0);
  assert.equal((await (await req('/api/customer/marketing-sms', c1)).json()).preferences.accepted, false);
  assert.equal(await fs.readFile(file, 'utf8'), original, 'reading SMS must not change customer data');
  assert.equal((await req('/api/customer/marketing-sms', c1, 'PATCH', { accepted: true, customerId: 'c2' })).status, 400);
  assert.equal((await req('/api/customer/marketing-sms', c1, 'PATCH', { accepted: true })).status, 200);
  assert.equal((await (await req('/api/customer/marketing-sms', c2)).json()).preferences.accepted, false);
  const preview = await (await req('/api/dashboard/marketing-sms/preview', admin, 'POST', { requestId: crypto.randomUUID(), title: 'Fictif', body: 'Pas d’envoi réel.', audience: 'all' })).json();
  assert.equal(preview.campaign.customers, 1);
  assert.equal((await req(`/api/dashboard/marketing-sms/campaigns/${preview.campaign.id}/send`, admin, 'POST', { confirm: true, maxSegments: preview.campaign.maxSegments })).status, 409);
  let db = JSON.parse(await fs.readFile(file, 'utf8')); assert.equal(db.marketingSms.jobs.length, 0);
  const stop = '/sms-stop/' + sms.stopToken('c1', { secret });
  const page = await req(stop); assert.equal(page.status, 200); assert.match(page.headers.get('content-security-policy'), /frame-ancestors 'none'/); assert.ok(!(await page.text()).includes('+336'));
  assert.equal(JSON.parse(await fs.readFile(file, 'utf8')).customers[0].smsMarketingPreferences.accepted, true, 'link scanners do not unsubscribe on GET');
  assert.equal((await req(stop, '', 'POST')).status, 400);
  assert.equal((await req(stop + '?confirm=1', '', 'POST')).status, 200);
  assert.equal(JSON.parse(await fs.readFile(file, 'utf8')).customers[0].smsMarketingPreferences.accepted, false);
  assert.equal((await req('/sms-stop/' + 'a'.repeat(43))).status, 404);
  await req('/api/customer/account', c1, 'DELETE'); db = JSON.parse(await fs.readFile(file, 'utf8')); assert.ok(!JSON.stringify(db.marketingSms).includes('"c1"'));
});
