const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs/promises');const os=require('node:os');const path=require('node:path');const {spawn}=require('node:child_process');const {once}=require('node:events');const {createCustomerSession}=require('./customer-session');
test('API marketing : permissions, brouillon privé, écritures limitées et téléphone protégé', {timeout:15000}, async t=>{
  const dir=await fs.mkdtemp(path.join(os.tmpdir(),'bibou-marketing-http-'));const dataFile=path.join(dir,'data.json');
  const original=JSON.stringify({customers:[{id:'c1',phone:'+33600000001',name:'Fictif',points:0}],orders:[],nextCustomerId:2,nextOrderNumber:1});await fs.writeFile(dataFile,original);
  const child=spawn(process.execPath,['--require',path.join(__dirname,'test-fixtures/sms-provider.cjs'),path.join(__dirname,'server.js')],{cwd:dir,env:{PATH:process.env.PATH,NODE_ENV:'test',PORT:'0',DATA_FILE_PATH:dataFile,SESSION_SECRET:'test-secret',RESTAURANT_DASHBOARD_PASSWORD:'test-password',TWILIO_ACCOUNT_SID:'FAKE',TWILIO_AUTH_TOKEN:'FAKE',TWILIO_VERIFY_SERVICE_SID:'FAKE'},stdio:['ignore','pipe','pipe']});
  t.after(async()=>{child.kill();if(child.exitCode===null)await once(child,'exit');await fs.rm(dir,{recursive:true,force:true});});
  const base=await new Promise((resolve,reject)=>{child.stdout.on('data',v=>{const match=String(v).match(/http:\/\/localhost:\d+/);if(match)resolve(match[0]+'/api');});child.on('error',reject);child.on('exit',code=>reject(new Error('API exit '+code)));});
  const req=(url,token='',method='GET',body)=>fetch(base+url,{method,headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});
  const client=createCustomerSession('c1','test-secret');
  for(const route of ['/dashboard/news','/dashboard/contest'])for(const auth of ['',client])assert.equal((await req(route,auth)).status,401);
  assert.deepEqual(await(await req('/contest')).json(),{status:'inactive'});
  assert.equal((await(await req('/news')).json()).items[2].kind,'contest');
  assert.equal(await fs.readFile(dataFile,'utf8'),original);
  const auth=(await(await req('/dashboard/auth/login','','POST',{password:'test-password'})).json()).token;
  const draftResponse=await req('/dashboard/contest',auth);assert.equal(draftResponse.headers.get('cache-control'),'no-store');
  assert.equal((await draftResponse.json()).launchLocked,true);
  assert.equal((await req('/dashboard/contest',auth,'PATCH',{revision:0,status:'published'})).status,400);
  assert.equal((await req('/dashboard/contest',auth,'PATCH',{revision:0,title:'Secret draft'})).status,200);
  assert.deepEqual(await(await req('/contest')).json(),{status:'inactive'});
  assert.equal((await req('/customer/contest/join',client,'POST',{})).status,409);
  const body={phone:'+33600000009',verifiedPhone:'+33600000009',phoneVerifiedAt:new Date().toISOString()};
  assert.equal((await req('/customers/c1',client,'PATCH',body)).status,400);
  assert.equal((await req('/customers/c1',client,'PATCH',{phone:'06 00 00 00 01',verifiedPhone:'+33600000001',name:'Test'})).status,200);
  const account=await(await req('/auth/me',client)).json();assert.equal(account.customer.verifiedPhone,undefined);assert.equal(account.customer.phone,'+33600000001');
  assert.equal((await req('/auth/sms/check','','POST',{phone:'0600000001',code:'000000'})).status,401);
  const verified=await(await req('/auth/sms/check','','POST',{phone:'0600000001',code:'123456'})).json();
  assert.equal(verified.customer.verifiedPhone,'+33600000001');assert.ok(verified.customer.firstPhoneVerifiedAt);
  const again=await(await req('/auth/sms/check','','POST',{phone:'0600000001',code:'123456'})).json();
  assert.equal(again.customer.firstPhoneVerifiedAt,verified.customer.firstPhoneVerifiedAt);
});
