const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),os=require('node:os'),path=require('node:path');
const {spawn}=require('node:child_process'),{once}=require('node:events');
const {createCustomerSession}=require('./customer-session'),{parisDateKey}=require('./availability');
const {validateAndPriceOrderItems}=require('./catalog');
test('amendments HTTP: auth, ownership, stale revisions, preparation lock, consent, refund ledger and persistence',{timeout:25000},async t=>{
 const dir=await fs.mkdtemp(path.join(os.tmpdir(),'bibou-amendment-test-')),file=path.join(dir,'data.json');
 const date=parisDateKey(new Date(Date.now()+86400000));
 const order=id=>({id,number:Number(id.slice(1)),customerId:'c1',customerName:'Client fictif',method:'pickup',serviceDate:date,slot:'19:00',status:'confirmed',createdAt:new Date().toISOString(),items:validateAndPriceOrderItems([{productId:'drink-coca',quantity:2,selections:[]}]).items,subtotal:3.6,total:3.6,discountRate:0,deliveryFee:0,payment:{status:'PAID'}});
 const loyaltyOrder=order('o4');loyaltyOrder.items=validateAndPriceOrderItems([{productId:'classique',quantity:2,selections:[{groupId:'protein',id:'viande'},{groupId:'salad',id:'sans-crudites'},{groupId:'sauces',id:'sans-sauce'}]}]).items;Object.assign(loyaltyOrder,{subtotal:19.8,total:19.8,loyaltyBasePoints:20,loyaltyWeightedBasePoints:20,loyaltyPointsAdded:20,loyaltyGrantedAt:new Date().toISOString(),loyaltyWeekStart:require('./loyalty').weekStartKey()});
 const expired=order('o3');expired.status='awaiting_customer';expired.amendment={revision:1,status:'pending',expiresAt:new Date(Date.now()-60000).toISOString()};
 await fs.writeFile(file,JSON.stringify({customers:[{id:'c1',name:'Client fictif',phone:'+33600000001',points:20,weeklyOrders:1,weeklyWeightedBasePoints:20,weeklyProgramPoints:20,loyaltyWeekStart:require('./loyalty').weekStartKey()},{id:'c2',name:'Autre',points:0}],orders:[order('o1'),order('o2'),expired,loyaltyOrder],reservations:[],nextOrderNumber:4,nextCustomerId:3}));
 const child=spawn(process.execPath,[path.join(__dirname,'server.js')],{cwd:dir,env:{PATH:process.env.PATH,PORT:'0',NODE_ENV:'test',DATA_FILE_PATH:file,SESSION_SECRET:'test-amendment',RESTAURANT_DASHBOARD_PASSWORD:'test-amendment-only'},stdio:['ignore','pipe','pipe']});
 t.after(async()=>{child.kill();if(child.exitCode===null)await once(child,'exit');await fs.rm(dir,{recursive:true,force:true});});
 let output='',errors='';child.stderr.on('data',d=>errors+=d);
 const base=await new Promise((resolve,reject)=>{child.stdout.on('data',d=>{output+=d;const m=output.match(/http:\/\/localhost:\d+/);if(m)resolve(m[0]+'/api');});child.on('error',reject);child.on('exit',c=>reject(Error(c+errors)));});
 const request=async(route,token='',method='GET',body)=>{const r=await fetch(base+route,{method,headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});return {status:r.status,data:await r.json()};};
 const customer=createCustomerSession('c1','test-amendment'),other=createCustomerSession('c2','test-amendment');
 const admin=(await request('/dashboard/auth/login','','POST',{password:'test-amendment-only'})).data.token;
 const input={revision:0,reason:'Boisson indisponible',items:[{productId:'drink-perrier',quantity:1,selections:[]}]};
 for(const token of ['',customer])assert.equal((await request('/dashboard/orders/o1/amendment-preview',token,'POST',input)).status,401);
 assert.equal((await request('/dashboard/amendment-catalog',customer)).status,401);
 assert.equal((await request('/dashboard/amendment-catalog',admin)).status,200);
 const preview=await request('/dashboard/orders/o1/amendment-preview',admin,'POST',input);assert.equal(preview.status,200);
 const proposal={...input,previewFingerprint:preview.data.fingerprint};
 assert.equal((await request('/dashboard/orders/o1/amendment',admin,'POST',proposal)).status,200);
 assert.equal((await request('/dashboard/orders/o1/amendment',admin,'POST',proposal)).status,409);
 for(const route of ['/dashboard/orders/o1','/orders/o1'])assert.equal((await request(route,admin,'PATCH',{status:'preparing'})).status,409);
 assert.equal((await request('/customer/orders/o1/amendment',other,'POST',{revision:1,decision:'accept'})).status,404);
 assert.equal((await request('/customer/orders/o1/amendment',customer,'POST',{revision:2,decision:'accept'})).status,409);
 const results=await Promise.all(['accept','accept'].map(decision=>request('/customer/orders/o1/amendment',customer,'POST',{revision:1,decision})));
 assert.ok(results.every(r=>r.status===200));assert.equal(results[0].data.order.total,1.8);
 assert.equal((await request('/dashboard/orders/o1',admin,'PATCH',{status:'preparing'})).status,200);
 assert.equal((await request('/dashboard/orders/o1/refund',customer,'POST',{amount:1.8,reference:'test'})).status,401);
 assert.equal((await request('/dashboard/orders/o1/refund',admin,'POST',{amount:1.8,reference:'test'})).status,200);
 const p2=(await request('/dashboard/orders/o2/amendment-preview',admin,'POST',input)).data;
 assert.equal((await request('/dashboard/orders/o2/amendment',admin,'POST',{...input,previewFingerprint:p2.fingerprint})).status,200);
 assert.equal((await request('/customer/orders/o2/amendment',customer,'POST',{revision:1,decision:'refuse'})).status,200);
 assert.equal((await request('/orders/o2',admin,'PATCH',{status:'preparing'})).status,409);
 const loyaltyInput={revision:0,reason:'Quantité réduite',items:[{productId:'classique',quantity:1,selections:loyaltyOrder.items[0].options}]};
 const lp=(await request('/dashboard/orders/o4/amendment-preview',admin,'POST',loyaltyInput)).data;
 assert.equal((await request('/dashboard/orders/o4/amendment',admin,'POST',{...loyaltyInput,previewFingerprint:lp.fingerprint})).status,200);
 assert.equal((await request('/customer/orders/o4/amendment',customer,'POST',{revision:1,decision:'accept'})).status,200);
 const persisted=JSON.parse(await fs.readFile(file,'utf8'));
 assert.equal(persisted.customers[0].points,10);assert.equal(persisted.customers[0].weeklyOrders,1);assert.equal(persisted.orders[3].loyaltyBasePoints,10);
 assert.equal(persisted.orders[0].paidTotal,3.6);assert.equal(persisted.orders[0].refund.status,'recorded');
 assert.equal(persisted.orders[1].refund.amount,3.6);assert.equal(persisted.orders[2].amendment.status,'expired');assert.equal(persisted.orders[2].refund.amount,3.6);
});
