const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),os=require('node:os'),path=require('node:path');
const {spawn}=require('node:child_process'),{once}=require('node:events');
const {createCustomerSession}=require('./customer-session');
test('Prix serveur garanti pour une précommande Android/web, reprise identique et aucun paiement réel', {timeout:20000},async t=>{
  const dir=await fs.mkdtemp(path.join(os.tmpdir(),'bibou-product-offer-'));
  const file=path.join(dir,'data.json'),customer={id:'fictional-product-offer',name:'Client Test',phone:'+33600000000',points:0,weeklyOrders:0,welcomeReward:{status:'used'}};
  const newcomer={...customer,id:'fictional-product-offer-welcome',phone:'+33600000001',welcomeReward:{status:'available',discountRate:0.1}};
  await fs.writeFile(file,JSON.stringify({customers:[customer,newcomer],orders:[],nextOrderNumber:1}));
  const child=spawn(process.execPath,['--require',path.join(__dirname,'test-fixtures/product-offer-clock.cjs'),path.join(__dirname,'server.js')],{cwd:dir,env:{PATH:process.env.PATH,NODE_ENV:'test',PORT:'0',DATA_FILE_PATH:file,SESSION_SECRET:'fictional-secret',FAKE_PRODUCT_OFFER_CLOCK:'true'},stdio:['ignore','pipe','pipe']});
  t.after(async()=>{child.kill();if(child.exitCode===null)await once(child,'exit');await fs.rm(dir,{recursive:true,force:true});});
  const base=await new Promise((resolve,reject)=>{let output='',errors='';child.stderr.on('data',data=>errors+=data);child.stdout.on('data',data=>{output+=data;const m=output.match(/http:\/\/localhost:(\d+)/);if(m)resolve(`http://127.0.0.1:${m[1]}/api`);});child.once('error',reject);child.once('exit',code=>reject(Error(`${code}: ${errors}`)));});
  const token=createCustomerSession(customer.id,'fictional-secret',{now:Date.parse('2026-10-10T12:00:00Z')});
  const request=async(route,body,sessionToken=token)=>{const response=await fetch(base+route,{method:body?'POST':'GET',headers:{Authorization:`Bearer ${sessionToken}`,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});return{status:response.status,data:await response.json()};};
  assert.equal((await request('/catalog')).data.products.find(p=>p.id==='dynamite').price,9.9);
  const product={productId:'dynamite',quantity:1,price:0,selections:[{groupId:'protein',id:'viande'},{groupId:'salad',id:'roquette'},{groupId:'sauces',id:'fixed-dynamite'}]};
  const input={customerId:customer.id,method:'pickup',serviceDate:'2026-10-10',slot:'19:00',slotGrid:20,items:[product],requestId:'attempt-fictional-dynamite-0001',total:0};
  const created=await request('/orders',input);
  assert.equal(created.status,201,JSON.stringify(created.data));
  assert.equal(created.data.order.subtotal,9.9);
  assert.equal(created.data.order.total,9.9);
  assert.equal(created.data.order.status,'awaiting_payment');
  assert.equal(created.data.order.payment,undefined);
  const replay=await request('/orders',input);
  assert.equal(replay.status,200);
  assert.equal(replay.data.order.id,created.data.order.id);
  assert.equal(replay.data.order.total,9.9);
  const normal=await request('/orders',{...input,serviceDate:'2026-10-11',requestId:'attempt-fictional-dynamite-0002'});
  assert.equal(normal.status,201,JSON.stringify(normal.data));
  assert.equal(normal.data.order.total,11.9);
  const newcomerToken=createCustomerSession(newcomer.id,'fictional-secret',{now:Date.parse('2026-10-10T12:00:00Z')});
  const welcome=await request('/orders',{...input,customerId:newcomer.id,requestId:'attempt-fictional-dynamite-0003'},newcomerToken);
  assert.equal(welcome.status,201,JSON.stringify(welcome.data));
  assert.equal(welcome.data.order.subtotal,9.9);
  assert.equal(welcome.data.order.total,8.91);
  assert.equal(welcome.data.order.welcomeRewardApplied,true);
  const db=JSON.parse(await fs.readFile(file,'utf8'));
  assert.equal(db.orders.length,3);
  assert.ok(db.orders.every(order=>!order.payment));
  assert.equal(db.customers[0].points,0);
  assert.equal(db.customers[1].welcomeReward.status,'available','la remise n’est pas consommée sans paiement');
});
