const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),os=require('node:os'),path=require('node:path'),crypto=require('node:crypto');
const {spawn}=require('node:child_process'),{once}=require('node:events'),{createCustomerSession}=require('./customer-session'),{parisDateKey}=require('./availability');
test('Uber HTTP : droits, devis, réservation unique, coupure réseau, signature, suivi et confidentialité',{timeout:25000},async t=>{
 const dir=await fs.mkdtemp(path.join(os.tmpdir(),'bibou-uber-test-')),file=path.join(dir,'data.json');
 const now=new Date(),parts=new Intl.DateTimeFormat('en-GB',{timeZone:'Europe/Paris',hour:'2-digit',minute:'2-digit',hour12:false}).format(now),slot=parts.slice(0,2)+':'+(Number(parts.slice(3))<30?'00':'30');
 const order=id=>({id,number:Number(id.slice(1)),customerId:'c1',customerName:'Client fictif',customerPhone:'0600000000',deliveryAddress:{address:'1 rue fictive',postalCode:'76600',city:'Le Havre'},method:'delivery',serviceDate:parisDateKey(now),slot,items:[{name:'Burger',price:10,quantity:1}],subtotal:10,total:14,status:'preparing',payment:{status:'PAID'},createdAt:now.toISOString()});
 await fs.writeFile(file,JSON.stringify({customers:[{id:'c1',name:'Client fictif',points:0}],orders:[order('o1')],reservations:[],nextOrderNumber:2,nextCustomerId:2}));
 const mock=path.join(dir,'mock.cjs');await fs.writeFile(mock,`global.fetch=async (url,opts)=>{if(url.includes('auth.uber.com'))return {ok:true,json:async()=>({access_token:'fake',expires_in:1000})};if(url.endsWith('/delivery_quotes'))return {ok:true,json:async()=>({id:'dqt_fake',fee:650,currency:'eur',expires:new Date(Date.now()+600000).toISOString(),dropoff_eta:new Date(Date.now()+600000).toISOString()})};if(url.endsWith('/deliveries'))throw Error('Simulated response loss');throw Error('Unexpected network call');};`);
 const child=spawn(process.execPath,['--require',mock,path.join(__dirname,'server.js')],{cwd:dir,env:{PATH:process.env.PATH,PORT:'0',NODE_ENV:'test',DATA_FILE_PATH:file,SESSION_SECRET:'fake-secret',RESTAURANT_DASHBOARD_PASSWORD:'test-only',UBER_DIRECT_ENABLED:'true',UBER_DIRECT_MODE:'test',UBER_DIRECT_CUSTOMER_ID:'fake-customer',UBER_DIRECT_CLIENT_ID:'fake',UBER_DIRECT_CLIENT_SECRET:'fake',UBER_DIRECT_WEBHOOK_SECRET:'test-key'},stdio:['ignore','pipe','pipe']});
 t.after(async()=>{child.kill();if(child.exitCode===null)await once(child,'exit');await fs.rm(dir,{recursive:true,force:true});});
 let output='',errors='';child.stderr.on('data',d=>errors+=d);const base=await new Promise((resolve,reject)=>{child.stdout.on('data',d=>{output+=d;const m=output.match(/http:\/\/localhost:\d+/);if(m)resolve(m[0]+'/api');});child.on('error',reject);child.on('exit',c=>reject(Error(c+errors)));});
 const request=async(route,token='',method='GET',body)=>{const r=await fetch(base+route,{method,headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});return {status:r.status,data:await r.json()};};
 const customer=createCustomerSession('c1','fake-secret'),admin=(await request('/dashboard/auth/login','','POST',{password:'test-only'})).data.token;
 assert.equal((await request('/dashboard/orders/o1/uber/quote',customer,'POST',{minutes:0})).status,401);
 assert.equal((await request('/dashboard/uber-status',admin)).data.configured,true);
 assert.equal((await request('/dashboard/orders/o1/uber/quote',admin,'POST',{minutes:0})).status,200);
 assert.equal((await request('/dashboard/orders/o1/uber/dispatch',admin,'POST',{confirm:true,quoteId:'dqt_fake',fee:1})).status,409);
 const input={confirm:true,quoteId:'dqt_fake',fee:650,acknowledgeTiming:true};
 const attempts=await Promise.all([request('/dashboard/orders/o1/uber/dispatch',admin,'POST',input),request('/dashboard/orders/o1/uber/dispatch',admin,'POST',input)]);assert.deepEqual(attempts.map(r=>r.status).sort(),[409,502]);
 let persisted=JSON.parse(await fs.readFile(file,'utf8'));assert.equal(persisted.orders[0].uberDirect.phase,'uncertain');
 assert.equal((await request('/dashboard/orders/o1',admin,'PATCH',{status:'cancelled'})).status,409);
 const event={kind:'event.delivery_status',customer_id:'fake-customer',live_mode:false,delivery_id:'del_fictive',created:new Date().toISOString(),data:{id:'del_fictive',external_id:persisted.orders[0].uberDirect.externalId,live_mode:false,status:'dropoff',updated:new Date().toISOString(),tracking_url:'https://www.ubereats.com/orders/fictive'}};
 const body=JSON.stringify(event),signature=crypto.createHmac('sha256','test-key').update(body).digest('hex');
 assert.equal((await fetch(base+'/uber-direct/webhook',{method:'POST',body,headers:{'x-uber-signature':'bad'}})).status,401);
 assert.equal((await fetch(base+'/uber-direct/webhook',{method:'POST',body,headers:{'x-uber-signature':signature}})).status,200);
 assert.equal((await fetch(base+'/uber-direct/webhook',{method:'POST',body,headers:{'x-uber-signature':signature}})).status,200);
 const own=(await request('/customer/orders',customer)).data.orders[0];assert.equal(own.status,'out_for_delivery');assert.equal(own.uberDirect,undefined);assert.equal(own.uberDelivery.status,'dropoff');assert.equal(own.total,14);
 persisted=JSON.parse(await fs.readFile(file,'utf8'));assert.equal(persisted.orders[0].uberDirect.deliveryId,'del_fictive');
});
