/* Restaurant-only CRM. Opening or previewing this screen never issues an offer. */
window.BibouCrm = function ({ root, settingsRoot, api, token, onUnauthorized, onLogout }) {
  let data = null, draft = null, dirty = false, busy = false, epoch = 0, days = 30;
  const esc = value => String(value ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const euro = n => n === null ? '—' : Number(n).toLocaleString('fr-FR',{style:'currency',currency:'EUR'});
  const date = n => new Date(n).toLocaleString('fr-FR',{timeZone:'Europe/Paris',dateStyle:'short',timeStyle:'short'});
  const labels = { inactive:'Faire revenir un client', birthday:'Fêter un anniversaire', large_order:'Remercier un gros panier', frequency:'Fidéliser les habitués', spend:'Valoriser les clients actifs' };
  const status = { available:'Disponible', reserved:'Paiement en cours', used:'Utilisée (paiement)', expired:'Expirée' };
  root.innerHTML = `<div class="crm-hero"><p class="eyebrow">LA RELATION CLIENT, DANS LA DURÉE</p><h2>Le bon geste, au bon moment.</h2><p>Fidélisez vos habitués et donnez envie de revenir. Vos campagnes s’appuient sur les commandes réellement payées, pas sur des données estimées.</p><span id="crm-state" class="crm-pill">Chargement…</span></div>
    <p class="crm-feedback" role="status" aria-live="polite"></p><div class="crm-toolbar"><h2>Votre activité</h2><label>Période <select id="crm-period"><option value="7">7 jours</option><option value="30" selected>30 jours</option><option value="90">90 jours</option><option value="365">365 jours</option></select></label></div>
    <div id="crm-metrics" class="metrics crm-metrics"></div><div id="crm-segments" class="crm-segments"></div>
    <section class="marketing-panel"><div class="crm-toolbar"><div><p class="eyebrow">VOS AUTOMATISMES</p><h2>Cinq façons de créer du lien</h2></div><button type="button" class="secondary-button" id="crm-preview">Prévisualiser le ciblage</button></div><p>Choisissez une remise, un seuil et un canal. Les règles restent en pause tant que le programme n’est pas activé dans Paramètres. Prévisualiser n’envoie rien et ne crée aucun bon.</p><div id="crm-rules"></div><button type="button" id="crm-save" class="login-button">Enregistrer les règles</button><p id="crm-dirty" class="crm-hint"></p></section>
    <section class="marketing-panel"><h2>Les résultats du marketing</h2><div id="crm-results" class="metrics crm-metrics"></div><div class="crm-table-wrap"><table class="crm-table"><caption>Offres créées sur la période et paiements associés sur cette même période</caption><thead><tr><th>Règle</th><th>Créées</th><th>Utilisées</th><th>Ventes associées</th><th>Remises</th></tr></thead><tbody id="crm-performance"></tbody></table></div><p class="crm-hint">Une utilisation est comptée uniquement après paiement et hors commande annulée. Les ventes associées ne prouvent pas un gain de chiffre d’affaires causé par la campagne. Les ouvertures, téléchargements et taux de lecture ne sont pas mesurés.</p><div id="crm-push-results"></div></section>
    <section class="marketing-panel"><h2>Dernières offres personnelles</h2><div id="crm-offers"></div></section>
    <p class="crm-hint">Statistiques issues uniquement de cette application. Les commandes SumUp ou Uber passées ailleurs ne sont pas importées. Les remboursements faits uniquement dans SumUp ne sont pas synchronisés : annulez aussi la commande côté restaurant. Les comptes supprimés ne figurent plus dans les segments clients.</p><button type="button" id="crm-reload" class="secondary-button">Recharger les données enregistrées</button>`;
  settingsRoot.innerHTML = `<div class="crm-hero"><p class="eyebrow">PARAMÈTRES RESTAURANT</p><h2>Vous gardez la main.</h2><p>Cadrez les automatismes et vérifiez les services disponibles. Aucun abonnement supplémentaire n’est créé ici.</p></div><p class="crm-feedback" role="status" aria-live="polite"></p>
    <section class="marketing-panel"><h2>Automatismes marketing</h2><label class="crm-check"><input type="checkbox" data-setting="enabled"> Activer le programme automatique</label><p>Une fois activé, le serveur évalue les règles toutes les 15 minutes, même si ce tableau est fermé. Les premiers bons peuvent être créés au prochain passage. En pause, aucun nouveau bon n’est créé ; les bons déjà accordés restent valables.</p><div class="marketing-grid">
    <label>Délai minimum entre deux offres à un client (jours)<input type="number" min="1" max="365" data-setting="cooldownDays"></label><label>Maximum d’offres par jour, toutes règles réunies<input type="number" min="1" max="1000" data-setting="dailyLimit"></label><label>Début de création des offres (heure de Paris)<input type="number" min="0" max="23" data-setting="startHour"></label><label>Fin de création des offres (heure de Paris)<input type="number" min="1" max="24" data-setting="endHour"></label></div><p class="crm-hint">Si plusieurs règles correspondent au même client, la première dans la liste est prioritaire. Un anniversaire du 29 février est ciblé uniquement les années bissextiles. Une commande jamais passée n’est pas considérée comme une inactivité.</p><button type="button" id="crm-settings-save" class="login-button">Enregistrer les paramètres</button></section>
    <section class="marketing-panel"><h2>Canaux & connexions</h2><div id="crm-connections"></div><p>Les promotions par push nécessitent à la fois l’accord aux offres personnalisées, l’accord aux notifications marketing et un téléphone compatible enregistré. Les SMS de connexion Twilio ne sont pas un canal publicitaire.</p></section>
    <section class="marketing-panel"><h2>Les données de vos clients</h2><p>Anniversaire facultatif (jour et mois uniquement) et accord aux offres personnalisées dans l’application client, à l’inscription puis dans Mon compte → Mes offres. Aucun ancien compte n’est inscrit automatiquement. Retrait du consentement possible à tout moment ; les bons déjà attribués restent valables. La suppression du compte efface ses données de ciblage et ses offres personnelles.</p><p>Cette installation gère un seul restaurant. Elle ne propose pas encore de séparation entre plusieurs établissements ou de rôles employés : ne partagez pas cet accès avec un autre commerce.</p></section>
    <section class="marketing-panel"><h2>Accès & sécurité</h2><p>Accès protégé par le mot de passe restaurant, session limitée à 12 heures. Les clés et mots de passe ne sont jamais affichés ici. Les sauvegardes restent dans leur rubrique dédiée.</p><button type="button" class="secondary-button" id="crm-logout">Se déconnecter de cet onglet</button></section>`;
  const q = selector => root.querySelector(selector);
  const message = value => [root,settingsRoot].forEach(r=>{r.querySelector('.crm-feedback').textContent=value;});
  const freeze = value => { busy=value; [root,settingsRoot].forEach(r=>r.querySelectorAll('button,input,select').forEach(el=>{el.disabled=value;})); };
  const markDirty = () => { dirty=true; q('#crm-dirty').textContent='Modifications non enregistrées.'; };
  async function request(path, method='GET', body) {
    const auth=token(), controller=new AbortController(), timeout=setTimeout(()=>controller.abort(),15000);
    try {
      const response=await fetch(api+path,{method,cache:'no-store',headers:{Authorization:`Bearer ${auth}`,'Content-Type':'application/json'},signal:controller.signal,...(body?{body:JSON.stringify(body)}:{})});
      if(auth!==token())throw Error('Session modifiée.');
      if(response.status===401){onUnauthorized();throw Error('Reconnectez-vous.');}
      const result=await response.json(); if(!response.ok)throw Error(result.error||'Action non enregistrée.'); return result;
    } finally {clearTimeout(timeout);}
  }
  const metric = (label,value) => `<article><div><strong>${esc(value)}</strong><small>${esc(label)}</small></div></article>`;
  function renderStats() {
    const s=data.statistics;
    q('#crm-state').textContent=data.settings.enabled?'Programme actif':'Programme en pause · aucun nouvel envoi';
    q('#crm-metrics').innerHTML=metric('clients ayant commandé',s.buyers)+metric('commandes payées',s.orders)+metric('ventes TTC, livraison comprise',euro(s.revenue))+metric('panier moyen payé',euro(s.averageBasket));
    q('#crm-segments').innerHTML=[['Comptes clients',s.customers],['Nouveaux sur la période',s.newCustomers],['Clients ≥ 2 achats sur la période',s.repeatBuyers],['Sans commande depuis 45 jours',s.inactive45],['N’ont jamais commandé',s.neverOrdered],['Accord aux offres personnalisées',s.consenting],['Anniversaires renseignés',s.birthdays]].map(([l,v])=>`<p><strong>${v}</strong><span>${l}</span></p>`).join('');
    q('#crm-results').innerHTML=metric('offres personnelles créées',s.offers)+metric('offres utilisées, hors annulations',s.used)+metric('utilisation des offres de la période',s.conversion===null?'—':`${s.conversion} %`)+metric('remises accordées',euro(s.discounts));
    q('#crm-performance').innerHTML=s.rules.map(r=>`<tr><th>${esc(labels[r.id])}</th><td>${r.issued}</td><td>${r.used}</td><td>${euro(r.revenue)}</td><td>${euro(r.discounts)}</td></tr>`).join('');
    const p=data.pushLast7Days;
    q('#crm-push-results').innerHTML=`<p class="crm-hint">Push CRM · suivi technique disponible sur 7 jours : ${p.queued} en attente, ${p.accepted} acceptés par Expo, ${p.provider_ok} transmis au fournisseur, ${p.failed} échecs, ${p.uncertain} statuts incertains, ${p.cancelled} annulés. Une transmission ne garantit ni affichage ni lecture.</p>`;
    q('#crm-offers').innerHTML=data.recentOffers.length?data.recentOffers.map(o=>`<div class="crm-offer"><div><strong>${esc(o.title)} · −${o.discountPercent} %</strong><p>${esc(o.customerName)} · ${date(o.createdAt)}</p></div><span class="crm-pill">${esc(status[o.status])}</span></div>`).join(''):'<p>Aucun bon n’a encore été créé. Les zéros affichés ne sont pas des données de démonstration.</p>';
    settingsRoot.querySelector('#crm-connections').innerHTML=[['Offres dans le compte client','Disponible sur le web et le mobile'],['Notifications push',data.channels.push?'Serveur activé · accord client et appareil requis':'Non activées sur le serveur'],['SMS promotionnels','Non connectés · aucun SMS envoyé'],['E-mails promotionnels','Non connectés · aucun e-mail envoyé'],['Dernière évaluation automatique',data.lastRunAt?date(data.lastRunAt):'Aucun passage enregistré']].map(([l,v])=>`<div class="crm-offer"><strong>${l}</strong><span>${esc(v)}</span></div>`).join('');
  }
  function field(r,key,label,options={}) {
    return `<label>${label}<input data-rule="${r.id}" data-field="${key}" type="${options.text?'text':'number'}" value="${esc(r[key]??'')}" ${options.text?'maxlength="65"':`min="${options.min??1}" max="${options.max??365}" step="${options.step??1}"`} ${options.placeholder?`placeholder="${options.placeholder}"`:''}></label>`;
  }
  function renderRules(previews=data.previews) {
    q('#crm-rules').innerHTML=draft.rules.map((r,i)=>{const p=previews.find(p=>p.id===r.id);return `<details class="crm-rule"><summary><span class="crm-rule-number">${i+1}</span><span><strong>${labels[r.id]}</strong><small>${r.enabled?'Règle activée':'En pause'} · ${p?.eligible??0} client(s) éligible(s) maintenant</small></span><span aria-hidden="true">⌄</span></summary><div class="crm-rule-body"><label class="crm-check"><input type="checkbox" data-rule="${r.id}" data-field="enabled" ${r.enabled?'checked':''}> Inclure cette règle dans le programme</label><div class="marketing-grid">${field(r,'title','Titre du bon',{text:true})}${r.type==='inactive'?field(r,'inactiveDays','Sans commande payée depuis (jours)',{max:730}):''}${r.type==='birthday'?'<p>Déclenchement la veille de l’anniversaire, heure de Paris. Une offre anniversaire maximum par année.</p>':''}${['large_order','frequency','spend'].includes(r.type)?field(r,'lookbackDays','Observer les derniers jours'):''}${r.type==='frequency'?field(r,'minOrders','Au moins combien de commandes ?',{max:1000,placeholder:'À définir'}):''}${['large_order','spend'].includes(r.type)?field(r,'minAmount',r.type==='large_order'?'Un panier de produits d’au moins (€)':'Produits commandés cumulés d’au moins (€)',{max:10000,step:0.01,placeholder:'À définir'}):''}${field(r,'discountPercent','Réduction sur les produits (%)',{max:50,placeholder:'À définir'})}${field(r,'minSubtotal','Minimum de produits pour utiliser le bon (€)',{min:0,max:10000,step:0.01})}${field(r,'validityDays','Validité du bon (jours)',{max:90})}<label>Canal<select data-rule="${r.id}" data-field="channel"><option value="in_app" ${r.channel==='in_app'?'selected':''}>Dans le compte client uniquement</option><option value="in_app_push" ${r.channel==='in_app_push'?'selected':''}>Compte client + push si autorisé</option></select></label></div><p class="crm-hint">Les seuils de panier/dépenses portent sur les produits avant remises, hors livraison, des commandes payées non annulées. Une seule remise : la plus avantageuse parmi ce bon, la bienvenue et Bibou +. La livraison offerte Bibou + reste applicable. Bon personnel à usage unique après paiement, y compris si la commande est ensuite annulée.</p><div class="crm-audience" data-audience="${r.id}">${audience(p)}</div></div></details>`;}).join('');
  }
  function audience(p) { return p?`<strong>Aperçu sans envoi</strong><p>${p.matched} correspondent · ${p.noConsent} sans accord · ${p.cooldown} en délai de sécurité · ${p.alreadyOffered} déjà récompensés pour cet événement.</p><p><strong>${p.eligible} éligible(s)</strong>${p.configured?'':' · remise ou seuil commercial à définir'}.</p>${p.sample.length?`<p>Exemples : ${p.sample.map(c=>esc(c.name)).join(', ')}</p>`:''}<small>Le nombre final peut diminuer selon le plafond quotidien et la priorité des règles.</small>`:''; }
  function renderForm() {
    renderRules(); settingsRoot.querySelectorAll('[data-setting]').forEach(el=>{el.type==='checkbox'?el.checked=draft[el.dataset.setting]:el.value=draft[el.dataset.setting];}); q('#crm-dirty').textContent='';
  }
  async function load(force=false) {
    if(busy||!token())return;
    if(dirty&&!force){message('Vos changements non enregistrés sont conservés. Enregistrez-les ou rechargez les données.');return;}
    const id=++epoch; freeze(true); message('Chargement du CRM…');
    try {const result=await request('/dashboard/crm?days='+days);if(id!==epoch)return;data=result;draft=JSON.parse(JSON.stringify(data.settings));dirty=false;renderStats();renderForm();message('Données actualisées à '+date(data.generatedAt)+'.');}
    catch(error){if(id===epoch)message(error.name==='AbortError'?'Connexion trop lente. Les données affichées peuvent être anciennes.':error.message);}
    finally{if(id===epoch)freeze(false);}
  }
  async function save() {
    if(busy||!draft)return;
    const confirmActivation=draft.enabled?window.confirm('Activer ces réglages ? Le serveur pourra créer les bons et envoyer les push autorisés au prochain passage. Vérifiez les remises, seuils et plafonds.'):false;
    if(draft.enabled&&!confirmActivation)return;
    const id=epoch;freeze(true);message('Enregistrement…');
    try{const result=await request('/dashboard/settings?days='+days,'PATCH',{...draft,confirmActivation});if(id!==epoch)return;data=result;draft=JSON.parse(JSON.stringify(data.settings));dirty=false;renderStats();renderForm();message(draft.enabled?'Réglages enregistrés. Programme actif : prochain passage sous 15 minutes.':'Réglages enregistrés. Programme en pause : aucun nouveau bon ni envoi.');}
    catch(error){if(id===epoch)message(error.name==='AbortError'?'Réponse trop lente. Rechargez pour vérifier si les réglages ont été enregistrés.':error.message);}
    finally{if(id===epoch)freeze(false);}
  }
  root.addEventListener('input',event=>{const el=event.target;if(!draft||busy||!el.dataset.rule)return;const r=draft.rules.find(r=>r.id===el.dataset.rule);r[el.dataset.field]=el.type==='checkbox'?el.checked:el.type==='number'?(el.value===''?null:Number(el.value)):el.value;markDirty();});
  settingsRoot.addEventListener('input',event=>{const el=event.target;if(!draft||busy||!el.dataset.setting)return;draft[el.dataset.setting]=el.type==='checkbox'?el.checked:Number(el.value);markDirty();});
  q('#crm-period').onchange=()=>{if(dirty){q('#crm-period').value=days;return message('Enregistrez ou rechargez vos modifications avant de changer de période.');}days=Number(q('#crm-period').value);void load();};
  q('#crm-preview').onclick=async()=>{if(busy||!draft)return;const id=epoch;freeze(true);message('Calcul de l’audience, sans envoi…');try{const r=await request('/dashboard/crm/preview','POST',draft);if(id!==epoch)return;r.previews.forEach(p=>{q(`[data-audience="${p.id}"]`).innerHTML=audience(p);});message('Aperçu calculé. Aucun bon créé, aucun message envoyé.');}catch(error){if(id===epoch)message(error.message);}finally{if(id===epoch)freeze(false);}};
  q('#crm-save').onclick=save; settingsRoot.querySelector('#crm-settings-save').onclick=save;
  q('#crm-reload').onclick=()=>{if(!dirty||window.confirm('Abandonner les modifications non enregistrées ?'))void load(true);};
  settingsRoot.querySelector('#crm-logout').onclick=onLogout;
  freeze(true);
  return {load(force=false){if(!data)busy=false;return load(force);},clear(){epoch++;data=draft=null;dirty=busy=false;['#crm-metrics','#crm-segments','#crm-rules','#crm-results','#crm-performance','#crm-push-results','#crm-offers'].forEach(s=>{q(s).innerHTML='';});settingsRoot.querySelector('#crm-connections').innerHTML='';message('');freeze(true);}};
};
